# Generated by Django 2.1.7 on 2019-03-22 10:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Food', '0004_auto_20190322_1055'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('substitute', models.ForeignKey(help_text='Product substituting the other', on_delete=django.db.models.deletion.CASCADE, related_name='substitute', to='Food.Product')),
                ('substituted', models.ForeignKey(help_text='Product to be substituted by', on_delete=django.db.models.deletion.CASCADE, related_name='substituted', to='Food.Product')),
                ('user', models.ForeignKey(help_text='User which substituted a product by another', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='favorite',
            unique_together={('substituted', 'substitute', 'user')},
        ),
    ]
