# Generated by Django 2.1.7 on 2019-03-15 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barcode', models.CharField(max_length=48, unique=True, verbose_name='barcode')),
                ('name', models.CharField(max_length=500, verbose_name='product name')),
                ('nutrition_grade', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E')], max_length=1, verbose_name='nutrition_grade')),
                ('url', models.URLField(unique=True)),
            ],
        ),
    ]
