# Generated by Django 2.1.7 on 2019-03-22 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Food', '0003_category_products'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('name',), 'verbose_name': 'category', 'verbose_name_plural': 'categories'},
        ),
    ]
